import os

os.environ.setdefault('DJANGO_SETTINGS_MODULE',
                      'dogMatcherApp.settings')

import django

django.setup()

from app.models import Dog


def populate():
    dogs = [
        {"breed": "Akita",
         "picture": "https://images.pexels.com/photos/35167/pexels-photo.jpg?w=940&h=650&auto=compress&cs=tinysrgb",
         "dogsize": 3,
         "grooming": 3, "beingalone": 4, "exercise": 3, "homesize": 3, "family": 3},
        {"breed": "Alaskan Malamute",
         "picture": "https://images.pexels.com/photos/67660/pexels-photo-67660.jpeg?w=940&h=650&auto=compress&cs=tinysrgb",
         "dogsize": 3,
         "grooming": 3, "beingalone": 4, "exercise": 3, "homesize": 3, "family": 2},
        {"breed": "American Pit Bull Terrier",
         "picture": "http://cdn1-www.dogtime.com/assets/uploads/2011/01/file_23052_pitbull-dog-breed-pittie-300x189.jpg",
         "dogsize": 2,
         "grooming": 1, "beingalone": 4, "exercise": 3, "homesize": 2, "family": 1},
        {"breed": "Basset Hound",
         "picture": "http://cdn3-www.dogtime.com/assets/uploads/2011/01/file_23010_basset-hound-300x189.jpg",
         "dogsize": 1,
         "grooming": 1, "beingalone": 2, "exercise": 1, "homesize": 1, "family": 1},
        {"breed": "Beagle",
         "picture": "http://cdn3-www.dogtime.com/assets/uploads/2011/01/file_23012_beagle-300x189.jpg", "dogsize": 1,
         "grooming": 1, "beingalone": 4, "exercise": 3, "homesize": 1, "family": 1},
        {"breed": "Belgian Sheepdog",
         "picture": "http://cdn3-www.dogtime.com/assets/uploads/2011/01/file_23174_belgian-sheepdog-300x189.jpg",
         "dogsize": 3,
         "grooming": 2, "beingalone": 2, "exercise": 3, "homesize": 2, "family": 1},
        {"breed": "Bichon Frise",
         "picture": "http://cdn1-www.dogtime.com/assets/uploads/2011/01/file_23136_bichon-frise-300x189.jpg",
         "dogsize": 1,
         "grooming": 3, "beingalone": 4, "exercise": 2, "homesize": 1, "family": 1},
        {"breed": "Bulldog",
         "picture": "http://cdn1-www.dogtime.com/assets/uploads/2011/01/file_23140_bulldog-300x189.jpg", "dogsize": 1,
         "grooming": 1, "beingalone": 2, "exercise": 2, "homesize": 1, "family": 1},
        {"breed": "Cardigan Welsh Corgi",
         "picture": "http://cdn1-www.dogtime.com/assets/uploads/2011/11/file_23294_cardigan-welsh-corgi-300x189.jpg",
         "dogsize": 1,
         "grooming": 2, "beingalone": 2, "exercise": 2, "homesize": 1, "family": 1},
        {"breed": "Cavalier King Charles Spaniel",
         "picture": "http://cdn2-www.dogtime.com/assets/uploads/2011/01/file_23100_cavalier-king-charles-spaniel-300x189.jpg",
         "dogsize": 1,
         "grooming": 1, "beingalone": 4, "exercise": 3, "homesize": 1, "family": 1},
        {"breed": "Chihuahua",
         "picture": "http://cdn2-www.dogtime.com/assets/uploads/2011/01/file_23102_chihuahua-300x189.jpg", "dogsize": 1,
         "grooming": 1, "beingalone": 4, "exercise": 1, "homesize": 1, "family": 1},
        {"breed": "Chinese Shar-Pei",
         "picture": "http://cdn2-www.dogtime.com/assets/uploads/2011/01/file_23142_chinese-shar-pei-300x189.jpg",
         "dogsize": 2,
         "grooming": 1, "beingalone": 1, "exercise": 2, "homesize": 1, "family": 3},
        {"breed": "Chow Chow",
         "picture": "http://cdn1-www.dogtime.com/assets/uploads/2011/01/file_23144_chow-chow-300x189.jpg", "dogsize": 3,
         "grooming": 3, "beingalone": 1, "exercise": 1, "homesize": 2, "family": 3},
        {"breed": "Cocker Spaniel",
         "picture": "http://cdn1-www.dogtime.com/assets/uploads/2011/01/file_22962_cocker-spaniel-300x189.jpg",
         "dogsize": 1,
         "grooming": 3, "beingalone": 4, "exercise": 2, "homesize": 1, "family": 2},
        {"breed": "Collie",
         "picture": "http://cdn3-www.dogtime.com/assets/uploads/2011/01/file_23186_collie-300x189.jpg", "dogsize": 2,
         "grooming": 2, "beingalone": 3, "exercise": 2, "homesize": 2, "family": 1},
        {"breed": "Dachshund",
         "picture": "http://cdn2-www.dogtime.com/assets/uploads/2011/01/file_23020_dachshund-dog-breed-300x189.jpg",
         "dogsize": 1,
         "grooming": 2, "beingalone": 2, "exercise": 2, "homesize": 1, "family": 1},
        {"breed": "Dalmatian",
         "picture": "http://cdn3-www.dogtime.com/assets/uploads/2011/01/file_23146_dalmatian-300x189.jpg", "dogsize": 2,
         "grooming": 1, "beingalone": 2, "exercise": 3, "homesize": 3, "family": 1},
        {"breed": "Doberman Pinscher",
         "picture": "http://cdn2-www.dogtime.com/assets/uploads/2011/01/file_22920_doberman-pinscher-300x189.jpg",
         "dogsize": 3,
         "grooming": 1, "beingalone": 3, "exercise": 2, "homesize": 2, "family": 2},
        {"breed": "English Foxhound",
         "picture": "http://cdn2-www.dogtime.com/assets/uploads/2011/01/file_23022_english-foxhound-300x189.jpg",
         "dogsize": 2,
         "grooming": 1, "beingalone": 1, "exercise": 3, "homesize": 3, "family": 1},
        {"breed": "English Springer Spaniel",
         "picture": "http://cdn1-www.dogtime.com/assets/uploads/2011/01/file_22970_english-springer-spaniel-300x189.jpg",
         "dogsize": 2,
         "grooming": 3, "beingalone": 4, "exercise": 3, "homesize": 3, "family": 1},
        {"breed": "English Toy Spaniel",
         "picture": "http://cdn2-www.dogtime.com/assets/uploads/2011/01/file_23106_english-toy-spaniel-300x189.jpg",
         "dogsize": 1,
         "grooming": 3, "beingalone": 4, "exercise": 1, "homesize": 1, "family": 3},
        {"breed": "Fox Terrier",
         "picture": "http://cdn3-www.dogtime.com/assets/uploads/2011/01/file_23094_fox-terrier-300x189.jpg",
         "dogsize": 1,
         "grooming": 3, "beingalone": 2, "exercise": 3, "homesize": 2, "family": 1},
        {"breed": "French Bulldog",
         "picture": "http://cdn3-www.dogtime.com/assets/uploads/2011/01/file_23150_french-bulldog-300x189.jpg",
         "dogsize": 1,
         "grooming": 1, "beingalone": 4, "exercise": 1, "homesize": 1, "family": 1},
        {"breed": "German Shepherd Dog",
         "picture": "http://cdn3-www.dogtime.com/assets/uploads/2011/01/file_23188_german-shepherd-dog-300x189.jpg",
         "dogsize": 3,
         "grooming": 1, "beingalone": 3, "exercise": 3, "homesize": 2, "family": 1},
        {"breed": "Golden Retriever",
         "picture": "http://cdn3-www.dogtime.com/assets/uploads/2011/01/file_22980_golden-retriever-300x189.jpg",
         "dogsize": 2,
         "grooming": 3, "beingalone": 4, "exercise": 3, "homesize": 3, "family": 1},
        {"breed": "Harrier",
         "picture": "http://cdn1-www.dogtime.com/assets/uploads/2011/01/file_23026_harrier-300x189.jpg", "dogsize": 2,
         "grooming": 1, "beingalone": 2, "exercise": 3, "homesize": 3, "family": 1},
        {"breed": "Havanese",
         "picture": "http://cdn3-www.dogtime.com/assets/uploads/2011/01/file_23108_havanese-300x189.jpg", "dogsize": 1,
         "grooming": 3, "beingalone": 4, "exercise": 2, "homesize": 1, "family": 1},
        {"breed": "Icelandic Sheepdog",
         "picture": "http://cdn2-www.dogtime.com/assets/uploads/2011/01/file_23274_icelandic-sheepdog-300x189.jpg",
         "dogsize": 2,
         "grooming": 3, "beingalone": 3, "exercise": 3, "homesize": 3, "family": 1},
        {"breed": "Italian Greyhound",
         "picture": "http://cdn1-www.dogtime.com/assets/uploads/2011/01/file_23110_italian-greyhound-300x189.jpg",
         "dogsize": 1,
         "grooming": 1, "beingalone": 4, "exercise": 3, "homesize": 1, "family": 1},
        {"breed": "Jack Russell Terrier",
         "picture": "http://cdn3-www.dogtime.com/assets/uploads/2011/01/file_23080_jack-russell-terrier-300x189.jpg",
         "dogsize": 1,
         "grooming": 2, "beingalone": 2, "exercise": 3, "homesize": 2, "family": 1},
        {"breed": "Kooikerhondje",
         "picture": "http://cdn1-www.dogtime.com/assets/uploads/2011/01/file_23266_kooikerhondje-300x189.jpg",
         "dogsize": 2,
         "grooming": 1, "beingalone": 3, "exercise": 3, "homesize": 1, "family": 3},
        {"breed": "Labradoodle",
         "picture": "http://cdn3-www.dogtime.com/assets/uploads/2011/01/file_23220_what-is-a-labradoodle-300x189.jpg",
         "dogsize": 3,
         "grooming": 1, "beingalone": 1, "exercise": 3, "homesize": 1, "family": 1},
        {"breed": "Labrador Retriever",
         "picture": "http://cdn3-www.dogtime.com/assets/uploads/2011/01/file_22988_labrador-retriever-300x189.jpg",
         "dogsize": 3,
         "grooming": 1, "beingalone": 3, "exercise": 3, "homesize": 3, "family": 1},
        {"breed": "Lakeland Terrier",
         "picture": "http://cdn1-www.dogtime.com/assets/uploads/2011/01/file_23072_lakeland-terrier-300x189.jpg",
         "dogsize": 1,
         "grooming": 3, "beingalone": 3, "exercise": 3, "homesize": 1, "family": 1},
        {"breed": "Maltese Shih Tzu",
         "picture": "http://cdn2-www.dogtime.com/assets/uploads/2011/01/file_23216_maltese-shih-tzu-300x189.jpg",
         "dogsize": 1,
         "grooming": 3, "beingalone": 2, "exercise": 2, "homesize": 1, "family": 2},
        {"breed": "Miniature Pinscher",
         "picture": "http://cdn3-www.dogtime.com/assets/uploads/2011/01/file_23116_miniature-pinscher-300x189.jpg",
         "dogsize": 1,
         "grooming": 1, "beingalone": 3, "exercise": 3, "homesize": 1, "family": 2},
        {"breed": "Miniature Schnauzer",
         "picture": "http://cdn3-www.dogtime.com/assets/uploads/2011/01/file_23074_miniature-schnauzer-300x189.jpg",
         "dogsize": 1,
         "grooming": 3, "beingalone": 1, "exercise": 3, "homesize": 1, "family": 2},
        {"breed": "Newfoundland",
         "picture": "http://cdn2-www.dogtime.com/assets/uploads/2011/01/file_22938_newfoundland-300x189.jpg",
         "dogsize": 3,
         "grooming": 3, "beingalone": 4, "exercise": 2, "homesize": 3, "family": 1},
        {"breed": "Norwich Terrier",
         "picture": "http://cdn3-www.dogtime.com/assets/uploads/2011/01/file_23078_norwich-terrier-300x189.jpg",
         "dogsize": 1,
         "grooming": 3, "beingalone": 3, "exercise": 3, "homesize": 1, "family": 1},
        {"breed": "Old English Sheepdog",
         "picture": "http://cdn3-www.dogtime.com/assets/uploads/2011/01/file_23190_old-english-sheepdog-300x189.jpg",
         "dogsize": 3,
         "grooming": 3, "beingalone": 3, "exercise": 3, "homesize": 1, "family": 1},
        {"breed": "Papillon",
         "picture": "http://cdn2-www.dogtime.com/assets/uploads/2011/01/file_23118_papillon-300x189.jpg", "dogsize": 1,
         "grooming": 2, "beingalone": 4, "exercise": 3, "homesize": 1, "family": 2},
        {"breed": "Pekingese",
         "picture": "http://cdn3-www.dogtime.com/assets/uploads/2011/01/file_23120_pekingese-300x189.jpg", "dogsize": 1,
         "grooming": 3, "beingalone": 2, "exercise": 1, "homesize": 1, "family": 3},
        {"breed": "Pointer",
         "picture": "http://cdn2-www.dogtime.com/assets/uploads/2011/01/file_22992_pointer-300x189.jpg", "dogsize": 2,
         "grooming": 1, "beingalone": 4, "exercise": 3, "homesize": 3, "family": 1},
        {"breed": "Pomeranian",
         "picture": "http://cdn2-www.dogtime.com/assets/uploads/2011/01/file_23122_pomeranian-300x189.jpg",
         "dogsize": 1,
         "grooming": 3, "beingalone": 4, "exercise": 1, "homesize": 1, "family": 3},
        {"breed": "Pug", "picture": "http://cdn2-www.dogtime.com/assets/uploads/2011/01/file_23124_pug-300x189.jpg",
         "dogsize": 1,
         "grooming": 1, "beingalone": 4, "exercise": 2, "homesize": 1, "family": 3},
        {"breed": "Rat Terrier",
         "picture": "http://cdn3-www.dogtime.com/assets/uploads/2011/01/file_23226_rat-terrier-dog-breed-300x189.jpg",
         "dogsize": 1,
         "grooming": 1, "beingalone": 2, "exercise": 3, "homesize": 1, "family": 1},
        {"breed": "Rhodesian Ridgeback",
         "picture": "http://cdn1-www.dogtime.com/assets/uploads/2011/01/file_23042_rhodesian-ridgeback-300x189.jpg",
         "dogsize": 3,
         "grooming": 1, "beingalone": 3, "exercise": 3, "homesize": 1, "family": 1},
        {"breed": "Rottweiler",
         "picture": "http://cdn3-www.dogtime.com/assets/uploads/2011/01/file_22942_rottweiler-300x189.jpg",
         "dogsize": 2,
         "grooming": 1, "beingalone": 4, "exercise": 3, "homesize": 3, "family": 1},
        {"breed": "Scottish Terrier",
         "picture": "http://cdn1-www.dogtime.com/assets/uploads/2011/01/file_23082_scottish-terrier-300x189.jpg",
         "dogsize": 1,
         "grooming": 3, "beingalone": 2, "exercise": 3, "homesize": 1, "family": 1},
        {"breed": "Shiba Inu",
         "picture": "http://cdn3-www.dogtime.com/assets/uploads/2011/01/file_23160_shiba-inu-300x189.jpg", "dogsize": 1,
         "grooming": 1, "beingalone": 1, "exercise": 2, "homesize": 1, "family": 2},
        {"breed": "Staffordshire Bull Terrier",
         "picture": "http://cdn1-www.dogtime.com/assets/uploads/2011/01/file_23292_staffordshire-bull-terrier-300x189.jpg",
         "dogsize": 1,
         "grooming": 1, "beingalone": 3, "exercise": 3, "homesize": 2, "family": 1},
        {"breed": "Tibetan Mastiff",
         "picture": "http://cdn2-www.dogtime.com/assets/uploads/2011/01/file_22952_tibetan-mastiff-300x189.jpg",
         "dogsize": 3,
         "grooming": 1, "beingalone": 4, "exercise": 1, "homesize": 3, "family": 1},
        {"breed": "Vizsla",
         "picture": "http://cdn1-www.dogtime.com/assets/uploads/2011/01/file_22996_vizsla-300x189.jpg", "dogsize": 2,
         "grooming": 1, "beingalone": 4, "exercise": 3, "homesize": 3, "family": 1},
        {"breed": "Whippet",
         "picture": "http://cdn2-www.dogtime.com/assets/uploads/2011/01/file_23048_whippet-300x189.jpg", "dogsize": 2,
         "grooming": 1, "beingalone": 3, "exercise": 3, "homesize": 1, "family": 1},
        {"breed": "Yorkshire Terrier",
         "picture": "http://cdn3-www.dogtime.com/assets/uploads/2011/01/file_23132_yorkshire-terrier-300x189.jpg",
         "dogsize": 1,
         "grooming": 3, "beingalone": 3, "exercise": 3, "homesize": 1, "family": 3}, ]

