# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-13 15:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grooming', models.IntegerField()),
                ('family', models.BooleanField()),
                ('homesize', models.IntegerField()),
                ('dogsize', models.IntegerField()),
                ('beingalone', models.IntegerField()),
                ('exercise', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
