# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-22 23:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170322_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingmetric',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Dog'),
        ),
    ]
